- name: create jenkins jobs
  hosts: localhost
  connection: local
  tasks:
    - name: Create a jenkins job using basic authentication
      community.general.jenkins_job:
        config: "{{ lookup('file', 'test.xml') }}"
        name: test
        password: afzal2001
        url: http://172.31.87.71:8080
        user: admin