- name: Template a file to /etc/file.conf
  ansible.builtin.template:
    src: sjob.jxml
    dest: /tmp/test.xml

- name: Create a jenkins job using basic authentication
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/test.xml') }}"
    name: {{item.job_name}}
    password: afzal2001
    url: http://172.31.87.71:8080
    user: admin